export const LOGIN_API = "/api/auth/login";
export const REGISTER_API = "/api/auth/register";
export const GET_PROFILE_API = "/api/auth/profile";
export const UPDATE_PROFILE_API = "/api/auth/updateProfile";
export const GET_USERS_API = "/api/auth/GetAllUsers";
export const LOG_OUT_API = "/api/auth/logout";
export const UPDATE_USER_PROFILE_BY_ADMIN = "/api/auth/updateUserByAdmin";
export const USER_IMAGE_URL = "/api/auth/image-url";
export const REFRESH_TOKEN_API = "/api/auth/refreshToken";
export const ADD_PET_API = "/api/pets";
export const GET_ALL_PETS_API = "/api/pets";
export const GET_PET_BY_ID_API = "/api/pets";
export const UPDATE_PET_API = "/api/pets";
export const GET_CURRENT_USER_PETS_API = "/api/pets/current";
export const GET_VETO_ACC_TO_APPROVE='/api/auth/unapprovedUsers'
export const APPROVE_VETO_ACC_API='/api/auth/approveUserByEmail'
export const SEND_RESET_PASS_MAIL='/api/auth/sendResetPasswordEmail'
export const VERIFY_RESET_PASS_TOKEN='/api/auth/verifyResetPasswordToken'
export const RESET_PASS='/api/auth/resetPassword'
export const PET_SHOP='/api/accessories'
export const SEARCH_IN_PET_SHOP_BY_NAME='/api/accessories/search'
export const SEARCH_VET_BY_NAME_API='/api/auth/search-veterinarians'
export const PET_VITAL_SIGNS='/api/vital-signs/pet'
export const HEALTH_ALERTS_API='/api/health-alerts/pet'
export const DISMISS_HEALTH_ALERTS_API='/api/health-alerts'
export const OVERVIEW_API='/api/overview/pet'
export const VET_APPOINTEMENT_API='/api/vet-appointments'
export const PET_GOAL_API='/api/petgoals'
export const PET_HEALTH_STATS='/api/health-stats'
export const SAVE_MESSAGING_TOKEN='/api/auth/messaging-token'
export const VACCINE_RECORD_API = '/api/vaccine_records'
export const SURGERY_RECORD_API = '/api/surgery_records'
export const MEDICAL_RECORD_API = '/api/medical_records'
export const VISIT_RECORD_API = '/api/visit_records'
export const SLEEP_PATTERN_API = '/api/sleep-patterns/pet'
export const ACTIVITY_PROPOSITION_API = '/api/activity-propositions'



