
export const SIGN_UP_PATH = '/sign_up';
export const SIGN_IN_PATH = '/sign_in';
export const ADMIN_DASH_PATH = '/dashboard_admin';
export const USER_MANAGEMENT_PATH = '/users_management';
export const CLIENT_DASH_PATH = '/dashboard_client';
export const VETO_DASH_PATH = '/dashboard_veterinarian';
export const MANAGE_VETO_REQUEST = '/manage_veto_request';
export const GPS_LOCATOR_PATH = '/gps_locator';
export const COMMUNITY_PATH = '/community';
export const ACTIVITY_TRACKER_PATH = '/activity_tracker';
export const BREED_AUTHENTICITY_PATH = '/breed_authenticity';
export const DEFINE_SAFE_ZONE_PATH = '/define_safe_zone';
export const HEALTH_MONITOR_PATH = '/health_monitor';
export const HEALTH_PASSPORT_PATH = '/health_passport';
export const MARKET_PLACE_PATH = '/market_place';
export const SET_ACTIVITY_GOALS_PATH = '/set_activity_goals';
export const VETO_NOTIFICATIONS_PATH = '/veto/notifications';
export const VETO_UPDATE_NOTES_PATH = '/veto/update_notes';
export const VETO_UPDATE_TREATMENT_PATH = '/veto/update_treatment';
export const PET_PROFILE = '/pet-profile/:id';
export const USER_PROFILE = '/profile';
export const PET_SHOP_MANAGEMENT = '/pet_shop_management'
export const SUBMIT_VETO_REQUEST = '/submit_veto_request';
export const RESET_PASS_REQUEST = '/resetPassword';
export const ASK_TO_RESET_PASS = '/ask_to_reset_pass';
export const CONSULT_VETO = '/consult_veto';

//http://localhost:3000/resetPassword?token=d671634b-27ea-41ab-9359-d26be772623b